name: Generate Pacman

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: DharshanPrakashP

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
